### ISSUE TITLE
其实我很想看那个演示的iphone App程序的

### ISSUE THREAD

**Issue by meteormatt** [felinx/d3status#1]
不知道哪里可以看到那个演示的iphone App程序。
现在这个好像只是后台的那个Server吧。
抓取暴雪服务器上的数据，然后发给前台JSON。

**Comment by felinx** [comment]
这个是server端的python代码，iPhone APP的ObjC代码是朋友写的，暂时不考虑开源。

**Comment by meteormatt** [comment]
好的。谢谢你的答复。
